name: GitHub Pages CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        ref: gh-pages
        submodules: recursive
        repository: DerilB/medplum
        fetch-depth: 1
        sparse-checkout-cone-mode: true

    - name: Build Jekyll site
      uses: actions/jekyll-build-pages@v1
      with:
        source: .
        destination: ./_site
        verbose: true

    - name: Upload build artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./_site
        name: github-pages
        retention-days: 1

  deploy:
    needs: build
    runs-on: ubuntu-22.04

    steps:
    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v4
      with:
        artifact_name: github-pages
        timeout: 600000
        error_count: 10
        reporting_interval: 5000

  report-build-status:
    needs: deploy
    runs-on: ubuntu-22.04

    steps:
    - name: Report build status
      run: |
        gh api -X POST "repos/$GITHUB_REPOSITORY/pages/telemetry" \
          -F github_run_id="$GITHUB_RUN_ID" \
          -F conclusion="success"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        CONCLUSION: success
